name: Deploy to FTP - autumn

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install lftp
        run: |
          apt-get update && apt-get install -y lftp

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to FTP - autumn
        run: |
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror --reverse --delete --verbose ./ /"
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
